service: aws-nodejs

provider:
  name: aws
  runtime: nodejs4.3

functions:
  blood:
    handler: main.fetch
    events:
      - http:
          path: get
          method: get
          cors: true
          response:
            headers:
              Content-Type: "application/json"
              Cache-Control: "'max-age=86400'"

